name: Nightly Build

on:
  schedule:
    - cron: '40 20 * * *'

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint auditjs
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Make test reports directory
        run: mkdir -p reports

      - name: Run tests
        run: yarn test-ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results
          path: reports/test-results.xml

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: coverage/lcov.info

      - name: Dogfood scan
        run: yarn run start ossi -u ${{ secrets.OSSI_USERNAME }} -p ${{ secrets.OSSI_TOKEN }} --whitelist dev-auditjs.json
